import:
  - globals/celsiusx-globals
  - globals/ue2-globals
  - catalog/terraform/aurora
  - catalog/terraform/eks-blue
  - catalog/terraform/eks-blue-override
  - catalog/terraform/vpc


vars:
  stage: dev

terraform:
  vars: {}

helmfile:
  vars: {}

components:
  terraform:
    "infra/vpc":
      vars:
        cidr_block: 10.10.0.0/18
