import:
  - globals/core-globals
  - globals/ue2-globals
  - catalog/eks-cluster
  - catalog/vpc


vars:
  stage: dev

terraform:
  vars: {}

helmfile:
  vars: {}

components:
  terraform:
    "vpc":
      vars:
        cidr_block: 10.10.0.0/18
